# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: '$(Build.BuildNumber)'
  imageName: '$(dockerId)/sparktodo-api:$(tagName)'

steps:
- script: dotnet build -c Release
  displayName: 'dotnet build'

- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker build Script'

- script: |
    docker login -u $(dockerId) -p $(pswd)
    docker push $(imageName)
  displayName: 'Push docker image'

- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: 'weihanli-vm'
    runOptions: inline

    inline: |
      kubectl set image deployment/sparktodo-api sparktodo-api=$(imageName) --record=true
