apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparktodo-api
  labels:
    app: sparktodo-api
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sparktodo-api
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      labels:
        app: sparktodo-api
    
    spec:
      containers:
      - name: sparktodo-api
        image: weihanli/sparktodo-api:latest
        imagePullPolicy: Always
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: my-secrets
                key: ConnectionStrings__Playground
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: "sparktodo-api"
  labels:
    app: "sparktodo-api"
spec:
  type: NodePort
  type: ClusterIP
  ports:
  - port: 8080
    nodePort: 31256
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: "sparktodo-api"
