apiVersion : apps/v1
kind: Deployment
metadata:
  name: "sparktodo-api"
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "sparktodo-api"
  template:
    metadata:
      labels:
        app: "sparktodo-api"
    spec:
      containers:
        - name: "sparktodo-api"
          image: "weihanli.azurecr.io/weihanli/sparktodo-api"
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]