apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
  name: sparktodo-api-ingress
spec:
  rules:
  - host: "sparktodo-api.weihanli.top"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sparktodo-api
            port:
              number: 80
  tls:
  - hosts:
    - sparktodo-api.weihanli.top