apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: sparktodo-api-ingress
spec:
  rules:
  - host: "sparktodo-api.lemonsharp.top"
    http:
      paths:
      - pathType: Prefix
        path: "/?(.*)"
        backend:
          service:
            name: sparktodo-api
            port:
              number: 80
      - pathType: Prefix
        path: "/monitor/?(.*)"
        backend:
          service:
            name: sparktodo-api
            port:
              number: 52323
  tls:
  - hosts:
    - sparktodo-api.lemonsharp.top
