name: dotnet-outdated

on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches: 
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
    - name: dotnet info
      run: dotnet --info
    - name: build
      run: dotnet build
    - name: install dotnet-outdated
      run: dotnet tool install --global dotnet-outdated-tool
    - name: Run dotnet-outdated
      run: dotnet-outdated -u
    - name: check for changes
      run: |
        if git diff --exit-code; then
          echo "has_changes=false" >> $GITHUB_ENV
        else
          echo "has_changes=true" >> $GITHUB_ENV
        fi
    - name: Build again and push changes
      if: ${{ env.has_changes == 'true' }}
      run: |
        dotnet build
        git config --global user.name "Weihan Li"
        git config --global user.email "weihanli@outlook.com"
        git commit -am "chore: upgrade packages"
        git push
    # - name: Create Pull Request
    #   id: cpr
    #   if: ${{ env.has_changes == 'true' }}
    #   uses: peter-evans/create-pull-request@v4
    #   with:
    #     commit-message: "Update NuGet Packages"
    #     title: 'Update NuGet Packages'
    #     body: >
    #       This PR updates the outdated NuGet packages.
    #     labels: automated-pr
    #     branch: update-nuget-dependencies
    #     delete-branch: true
    #     base: master
    # - name: Create pull request outputs
    #   if: ${{ steps.cpr.outputs.pull-request-number }}
    #   run: |
    #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
    #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
