name: dotnet-format

on: "push"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: build
      run: dotnet build
    - name: format
      run: dotnet format
    - name: Commit files
      shell: bash
      run: |
        set ErrorActionPreference Continue
        git add -A
        git diff HEAD --exit-code
        rc = $?
        if [$rc != 0]
        then
          git config --local user.name "github-actions[bot]"
          git config --local user.email "weihanli@outlook.com"
          git commit -m 'Automated dotnet-format update from $env:GITHUB_REF_NAME $env:GITHUB_SHA'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin $env:GITHUB_REF_NAME
        fi
 
